# Generated by Django 3.2.16 on 2023-09-10 13:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0003_auto_20230910_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='favorited',
            field=models.ManyToManyField(blank=True, related_name='favorited', to=settings.AUTH_USER_MODEL, verbose_name='Избранное'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='shopping_cart',
            field=models.ManyToManyField(blank=True, related_name='shopping_card', to=settings.AUTH_USER_MODEL, verbose_name='Список покупок'),
        ),
    ]
